server {
    listen 80;
    server_name smishing-detect-kdt2.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name smishing-detect-kdt2.cloud;

    ssl_certificate /etc/letsencrypt/live/smishing-detect-kdt2.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smishing-detect-kdt2.cloud/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://fastapi:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /grafana/ {
        proxy_pass http://grafana:3000/grafana/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_read_timeout 300s;
        proxy_connect_timeout 10s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
